#!/bin/bash

echo '\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[norsk]{babel}

\author{}
\title{}

\begin{document}

\maketitle

\section{}

\end{document}' > "${PWD##*/}".tex

echo '#!/bin/sh
pdftotext *.pdf - | wc -w' > wordcount.sh

chmod +x wordcount.sh
